apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-receiver-cfg-cm
data:
  config.yaml: |
    server:
      bind: ":8080"
      tls: true
      certFile: "/config/cert.crt"
      keyFile: "/config/cert.key"

    gitlab:
      token: "<gitlab-webhook-token>"

    direktiv:
      endpoint: http://<direktiv-url>/api/namespaces/<namespace>/broadcast
      insecureSkipVerify: true
      token: "<token>"
      event-on-error: true
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    .........
    -----END CERTIFICATE-----
  cert.key: |
    -----BEGIN CERTIFICATE-----
    .........
    -----END CERTIFICATE-----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-receiver
  labels:
    app: gitlab-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-receiver
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: gitlab-receiver
    spec:
      volumes:
      - name: gitlabconf
        configMap:
          name: gitlab-receiver-cfg-cm
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532        
        runAsGroup: 65532
      containers:
        - name: gitlab-receiver
          image: wwonigkeit/gitlab-receiver:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: gitlabconf
            mountPath: "/config"
            readOnly: false
---
apiVersion: v1 
kind: Service
metadata:
  name: gitlab-receiver-service
spec:
  selector:
    app: gitlab-receiver
  ports:
    - port: 8080