apiVersion: v1
kind: ConfigMap
metadata:
  name: linode-receiver-cfg-cm
data:
  config.yaml: |
    linode:
      linodeAuthToken: <linode-token>

    direktiv:
      endpoint: http://<direktiv-url>/api/namespaces/<namespace>/broadcast
      insecureSkipVerify: true
      token: "<token>"
      event-on-error: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linode-receiver
  labels:
    app: linode-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linode-receiver
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: linode-receiver
    spec:
      volumes:
      - name: linodeconf
        configMap:
          name: linode-receiver-cfg-cm
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532        
        runAsGroup: 65532
      containers:
        - name: linode-receiver
          image: wwonigkeit/linode-receiver:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: linodeconf
            mountPath: "/config"
            readOnly: false